round:
  endTime: 60
  fallTime: 30
  teamCount: 0
  wallCount: 0
localization:
  language: RU
  minutes: мин
  soonGameMessage: Игра скоро начнётся!
  startGameMessage: Игра началась!
  startGameAlert: до начала игры!
  wallFallAlert: Внимание! Стены упадут через
  wallFallWarring: Внимание! Скоро упадут стены, возможно пролагивание сервера!
  wallFallTimer: до падения стен!
  wallFallMessage: Стены упали!
  roundEndAlert: Внимание! До конца игры
  victoryTeamMessage: Победила команда
  nobodyVictoryMessage: Никто не победил!
  endGameMessage: Игра закончилась!

  gameAlreadyStartedError: Игра уже началась!
  teamSizeError: Невозможно запустить игру так как недостаточно команд!
  roundStartedError: Невозможно выполнить так как раунд уже запущен!
  argumentError: Невозможно выполнить так как недопустимый набор аргументов!
  teamNotFoundError: Команда не была найдена!
  notPlayerError: Не игрок!