round:
  endTime: 60
  fallTime: 5
  teamCount: 0
  wallCount: 0
localization:
  roundStartedError: Невозможно выполнить так как раунд уже запущен!
  argumentError: Невозможно выполнить так как недопустимый набор аргументов!
  teamNotFoundError: Команда не была найдена!
  notPlayerError: Не игрок!