name: Thewalls
version: ${project.version}
main: plugin.thewalls.Main
api-version: 1.16
commands:
  team:
    description: (add|join|leave|list|remove|setSpawnPoint)
    usage: /<command>
    permission-message: У вас нет прав на выполнение команды!
  wall:
    description: (add|save|remove|create|destroy|createAll|destroyAll)
    usage: /<command>
    permission-message: У вас нет прав на выполнение команды!
  round:
    description: (start|stop|info|setEndTime|setFallTime)
    usage: /<command>
    permission-message: У вас нет прав на выполнение команды!