mapsSize: 0
currentMap: null
maps: {}
localization:
  limitBlockYPlaceError: Вы достигли предела!
  portalCreateError: На данной карте нельзя создавать порталы!
  respawnPlayer: был успешно воскрешён!
  teamSelectorItemName: Выбрать команду
  teamSelectorItemDescription: Используйте этот предмет для выбора команды
  teamGUIName: Команды
  teamGUINotHaveSpawningPoint: Не имеет точки спавна!
  teamGUINotHaveEntries: Не имеет участников!
  soonGameMessage: Игра скоро начнётся!
  startGameAlert: До начала игры
  startGameMessage: Игра началась!
  endGameWinMessage: Победила команда
  endGameNoOneWinMessage: Никто не победил
  stopGameMessage: Игра закончилась!
  roundTimerBeforeWallsFallen: Время до падения стен
  roundTimerBeforeEnd: Время до конца игры
  wallsFallenTitle: Стены упали!
  wallsFallenSubtitle: Попробуйте выжить...
  defaultTimerText: Добро пожаловать на TheWalls!
  roundAwakeTimerText: Время до начала игры
  roundStartTimerText: Время до падения стен
  roundWallsFallenTimerText: Время до конца игры
  mapCommandAdd: Вы успешно добавили карту
  mapCommandRemove: Вы успешно удалили карту
  mapCommandSet: Вы успешно установили текущую карту
  mapCommandSave: Все карты были успешно сохранены
  mapCommandSetup: Текущая карта была настроена успешно
  mapCommandSettingsBarColor: Цвет таймера успешно установлен
  mapCommandSettingsSpawnLocation: Установлена локация точка лобби
  mapCommandSettingsRoundAwakeTime: Установлено время запуска раунда
  mapCommandSettingsMaxRoundTime: Установлено максимальное время раунда
  mapCommandSettingsWallsFallenTime: Установлено время падения стен
  mapCommandSettingsMaxBlockPlaceY: Установлена максимальная высота размещения блока по Y
  mapCommandSettingsWorldBorderMaxSize: Установлен максимальный размер барьера
  mapCommandSettingsWorldBorderMinSize: Установлен минимальный размер барьера
  mapCommandSettingsWorldBorderCanterLocation: Установлен центр барьера
  mapCommandSettingsCanCreatePortal: Возможность создания портала
  teamCommandAdd: Команда была успешно добавлена!
  teamCommandRemove: Команда была успешно удалена!
  teamCommandSetSpawnPoint: Точка спавна команды была успешно установлена!
  wallCommandAdd: Стена была успешно добавлена!
  wallCommandRemove: Стена была успешно удалена!
  wallCommandCreate: Стена была успешно создана!
  wallCommandSave: Стена была успешно сохранена!
  roundCommandDevMove: Режим разработчика