name: Thewalls
version: ${project.version}
main: com.nikyoff.thewalls.Main
api-version: 1.16
permissions:
  TheWalls.setup:
    description: setup game
    default: op
commands:
  map:
    description: (add|remove|set|save|setup|settings)
    usage: /<command> [add|remove|set|save|setup|settings]
    permission: TheWalls.setup
  team:
    description: (add|remove|setSpawnPoint|book|join|leave)
    usage: /<command> [add|remove|setSpawnPoint|book|join|leave]
    permission: TheWalls.setup
  wall:
    description: (add|remove|create|save)
    usage: /<command> [add|remove|create|save]
    permission: TheWalls.setup
  round:
    description: (start|stop|check|respawn|devMode|debugRound|debugMap|debugTeams|debugWalls)
    usage: /<command> [start|stop|check|respawn|devMode|debugRound|debugMap|debugTeams|debugWalls]
    permission: TheWalls.setup